name: Glitch Merge to Master
on:
  push:
    branches: [ glitch ]
  workflow_dispatch:
  repository_dispatch:
jobs:
  mergetomaster:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.repos.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_message: context.payload.head_commit.message,
              head: 'glitch',
              base: 'master',
            });
